language: java

jdk:
- oraclejdk7

branches:
only:
- master

install: mvn clean package -Dmaven.test.skip=true

script: ls && pwd && cd target & zip ci-game.hpi.zip ci-game.hpi & cd ..

deploy:
  provider: releases
  api-key: "ae813b6182d865c1019eaccee6f82bb89ab95500"
  file: 
   - "target/ci-game.hpi.zip"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: IDeaSCo/rockstar-plugins-jenkins-ci-game
