language: java

jdk:
- oraclejdk7

branches:
only:
- master

install: mvn clean package -Dmaven.test.skip=true

script: cd target && zip ci-game.hpi.zip ci-game.hpi && cd ..

deploy:
  provider: releases
  api-key: "15116853a7ec2b2ba04f9ee612f05941ee9b36d4"
  file: 
   - "target/ci-game.hpi.zip"
   - "target/ci-game.hpi"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: IDeaSCo/rockstar-plugins-jenkins-ci-game
