language: java

jdk:
- oraclejdk7

branches:
only:
- master

install: mvn clean install

deploy:
  provider: releases
  api-key: "ae813b6182d865c1019eaccee6f82bb89ab95500"
  file: 
   - "1.21/ci-game-1.21.hpi"
   - "target/ci-game.hpi"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: IDeaSCo/rockstar-plugins-jenkins-ci-game
